name: ejerciciotres
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ejemplopng.png
    - assets/paisaje.jpg
    - assets/Perfil.jpg
    - assets/piloto.jpg
    - assets/Praga.jpg
    - assets/retrato.jpeg
    - assets/PAISAJEmORADO.jpg
    - assets/paisajemorao.jpg
    - assets/Nuevo.png
