export 'package:ejerciciotres/screens/enlace5.dart';
export 'package:ejerciciotres/screens/enlace6.dart';

export 'package:ejerciciotres/screens/enlace7.dart';
export 'package:flutter/material.dart';
export 'package:ejerciciotres/screens/home_screen.dart';
export 'package:ejerciciotres/screens/paginaUsuario.dart';
export 'package:ejerciciotres/screens/enlace1.dart';
export 'package:ejerciciotres/screens/enlace2.dart';
export 'package:ejerciciotres/screens/enlace3.dart';
export 'package:ejerciciotres/screens/enlace4.dart';
export 'package:ejerciciotres/screens/juegoSieteYMedia.dart';
export 'package:ejerciciotres/screens/header.dart';
export 'package:ejerciciotres/screens/iconos.dart';
export 'package:ejerciciotres/screens/infoUsuarios.dart';
export 'package:ejerciciotres/screens/menuLateral.dart';
export 'package:ejerciciotres/screens/historias.dart';
export 'package:ejerciciotres/screens/publicaciones.dart';
export 'package:ejerciciotres/screens/formulario.dart';